"""initial schema

Revision ID: 0a3afd7ba279
Revises:
Create Date: 2026-08-18 11:54:49.218111

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a3afd7ba279"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "backend",
            sa.Enum("imap", name="backend_kind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("use_ssl", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("secret_ref", sa.String(length=255), nullable=False),
        sa.Column(
            "health",
            sa.Enum(
                "unknown",
                "ok",
                "read_only",
                "down",
                name="account_health",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("health_detail", sa.Text(), nullable=True),
        sa.Column("health_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cache_bodies", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name"),
    )
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_account_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("subject_kind", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.Column("verb", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "seq"),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_event_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_subject", ["tenant_id", "subject_kind", "subject_id"], unique=False
        )

    op.create_table(
        "producer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "agent", "service", "person", name="producer_kind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name"),
    )
    with op.batch_alter_table("producer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_producer_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "account_capability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("declared", sa.Boolean(), nullable=False),
        sa.Column("probed_present", sa.Boolean(), nullable=True),
        sa.Column("probed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "name"),
    )
    with op.batch_alter_table("account_capability", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_capability_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "assessment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "subject_kind",
            sa.Enum("message", "bundle", name="subject_kind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum(
                "mechanical", "producer", name="assessment_origin", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("producer_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(origin != 'producer') OR (producer_id IS NOT NULL)",
            name="ck_producer_assessment_has_producer",
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.create_index(
            "ix_assessment_subject", ["tenant_id", "subject_kind", "subject_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assessment_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "container",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("delimiter", sa.String(length=4), nullable=True),
        sa.Column("special_use", sa.String(length=32), nullable=True),
        sa.Column("selectable", sa.Boolean(), nullable=False),
        sa.Column("uidvalidity", sa.BigInteger(), nullable=True),
        sa.Column("uidnext", sa.BigInteger(), nullable=True),
        sa.Column("highestmodseq", sa.BigInteger(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("last_full_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_incremental_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "name"),
    )
    with op.batch_alter_table("container", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_container_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "grant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_grant_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("message_id_header", sa.String(length=512), nullable=True),
        sa.Column("content_key", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("date_header", sa.DateTime(timezone=True), nullable=True),
        sa.Column("from_address", sa.String(length=320), nullable=True),
        sa.Column("from_display", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("has_attachments", sa.Boolean(), nullable=False),
        sa.Column("list_id", sa.String(length=255), nullable=True),
        sa.Column("has_list_unsubscribe", sa.Boolean(), nullable=False),
        sa.Column("in_reply_to", sa.String(length=512), nullable=True),
        sa.Column("preview", sa.Text(), nullable=True),
        sa.Column(
            "parse_status",
            sa.Enum(
                "ok",
                "partial",
                "unparseable",
                name="parse_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "content_key"),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(
            "ix_message_from", ["tenant_id", "account_id", "from_address"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_message_list_id"), ["list_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_message_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "bundle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.Column(
            "action_kind",
            sa.Enum("state", "draft", name="action_kind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "operation",
            sa.Enum(
                "move",
                "add_flag",
                "remove_flag",
                "delete",
                name="operation",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("target_container_id", sa.Integer(), nullable=True),
        sa.Column("flag", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "accepted",
                "applied",
                "partially_applied",
                "rejected",
                "withdrawn",
                "superseded",
                "expired",
                name="bundle_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_id", sa.Integer(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(operation != 'move') OR (target_container_id IS NOT NULL)",
            name="ck_move_needs_target",
        ),
        sa.CheckConstraint(
            "(operation NOT IN ('add_flag', 'remove_flag')) OR (flag IS NOT NULL)",
            name="ck_flag_op_needs_flag",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"],
            ["producer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_container_id"],
            ["container.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bundle", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bundle_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_bundle_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "finding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column(
            "finding_class",
            sa.Enum(
                "mechanical",
                "interpretation",
                name="finding_class",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_finding_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "grant_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grant_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grant_id", "account_id"),
    )
    with op.batch_alter_table("grant_account", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_grant_account_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "message_address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "from",
                "to",
                "cc",
                "bcc",
                "reply_to",
                name="address_role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message_address", schema=None) as batch_op:
        batch_op.create_index("ix_message_address", ["tenant_id", "address"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_message_address_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "message_body",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("text_plain", sa.Text(), nullable=True),
        sa.Column("text_from_html", sa.Text(), nullable=True),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("bytes_stored", sa.Integer(), nullable=False),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    with op.batch_alter_table("message_body", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_body_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "placement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("container_generation", sa.Integer(), nullable=False),
        sa.Column("modseq", sa.BigInteger(), nullable=True),
        sa.Column("flags", sa.Text(), nullable=False),
        sa.Column("internaldate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_id"],
            ["container.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("container_id", "container_generation", "uid"),
    )
    with op.batch_alter_table("placement", schema=None) as batch_op:
        batch_op.create_index(
            "ix_placement_live", ["tenant_id", "container_id", "gone_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_placement_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "suggestion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bundle_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("source_container_id", sa.Integer(), nullable=False),
        sa.Column("premise_container_generation", sa.Integer(), nullable=False),
        sa.Column("premise_uid", sa.BigInteger(), nullable=False),
        sa.Column("premise_modseq", sa.BigInteger(), nullable=True),
        sa.Column("premise_flags_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "excluded",
                "accepted",
                "applied",
                "rejected",
                "withdrawn",
                "superseded",
                "stale",
                "expired",
                "failed",
                name="suggestion_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("stale_detail", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundle.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_container_id"],
            ["container.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bundle_id", "message_id"),
    )
    with op.batch_alter_table("suggestion", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_suggestion_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_suggestion_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "apply_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("suggestion_id", sa.Integer(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "precondition",
            sa.Enum(
                "conditional", "best_effort", name="precondition", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "guarantee_obtained",
            sa.Enum(
                "conditional",
                "best_effort",
                name="guarantee_obtained",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "applied",
                "refused_stale",
                "failed",
                name="apply_outcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("server_response", sa.Text(), nullable=True),
        sa.Column("resulting_uid", sa.BigInteger(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["suggestion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("apply_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_apply_attempt_tenant_id"), ["tenant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("apply_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apply_attempt_tenant_id"))

    op.drop_table("apply_attempt")
    with op.batch_alter_table("suggestion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suggestion_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_suggestion_status"))

    op.drop_table("suggestion")
    with op.batch_alter_table("placement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_placement_tenant_id"))
        batch_op.drop_index("ix_placement_live")

    op.drop_table("placement")
    with op.batch_alter_table("message_body", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_body_tenant_id"))

    op.drop_table("message_body")
    with op.batch_alter_table("message_address", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_address_tenant_id"))
        batch_op.drop_index("ix_message_address")

    op.drop_table("message_address")
    with op.batch_alter_table("grant_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grant_account_tenant_id"))

    op.drop_table("grant_account")
    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finding_tenant_id"))

    op.drop_table("finding")
    with op.batch_alter_table("bundle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bundle_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bundle_status"))

    op.drop_table("bundle")
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_message_list_id"))
        batch_op.drop_index("ix_message_from")

    op.drop_table("message")
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grant_tenant_id"))

    op.drop_table("grant")
    with op.batch_alter_table("container", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_container_tenant_id"))

    op.drop_table("container")
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assessment_tenant_id"))
        batch_op.drop_index("ix_assessment_subject")

    op.drop_table("assessment")
    with op.batch_alter_table("account_capability", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_capability_tenant_id"))

    op.drop_table("account_capability")
    with op.batch_alter_table("producer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_producer_tenant_id"))

    op.drop_table("producer")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_subject")
        batch_op.drop_index(batch_op.f("ix_audit_event_tenant_id"))

    op.drop_table("audit_event")
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_tenant_id"))

    op.drop_table("account")
    op.drop_table("tenant")
    # ### end Alembic commands ###
